In [12]:
import pandas as pd
from pandasql import sqldf
import numpy as np

#### Load the AWProduct.csv file into a Pandas Dataframe. Name the Dataframe df

In [13]:
df = pd.read_csv("AWProduct.csv")
df.shape

(606, 25)

#### Using SQL: Display the first 10 rows of the Dataframe. Only show the following columns: ProductKey, ProductAlternateKey, ProductSubcategoryKey, ProductName

In [14]:
sqldf("SELECT * FROM df LIMIT 10")

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,ProductName,StandardCost,FinishedGoodsFlag,Color,SafetyStockLevel,...,DaysToManufacture,ProductLine,DealerPrice,Class,Style,ModelName,ProductDescription,StartDate,EndDate,Status
0,1,AR-5381,None,None,None,Adjustable Race,None,0,None,1000,...,0,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
1,2,BA-8327,None,None,None,Bearing Ball,None,0,None,1000,...,0,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
2,3,BE-2349,None,None,None,BB Ball Bearing,None,0,None,800,...,1,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
3,4,BE-2908,None,None,None,Headset Ball Bearings,None,0,None,800,...,0,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
4,5,BL-2036,None,None,None,Blade,None,0,None,800,...,1,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
5,6,CA-5965,None,None,None,LL Crankarm,None,0,Black,500,...,0,None,None,L,None,None,None,2003-07-01 00:00:00.000,None,Current
6,7,CA-6738,None,None,None,ML Crankarm,None,0,Black,500,...,0,None,None,M,None,None,None,2003-07-01 00:00:00.000,None,Current
7,8,CA-7457,None,None,None,HL Crankarm,None,0,Black,500,...,0,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
8,9,CB-2903,None,None,None,Chainring Bolts,None,0,Silver,1000,...,0,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current
9,10,CN-6137,None,None,None,Chainring Nut,None,0,Silver,1000,...,0,None,None,None,None,None,None,2003-07-01 00:00:00.000,None,Current

#### Using Pandas: Display the first 10 rows of the Dataframe. Only show the following columns: ProductKey, ProductAlternateKey, ProductSubcategoryKey, ProductName

In [15]:
df[['ProductKey', 'ProductAlternateKey', 'ProductSubcategoryKey', 'ProductName']].head(10)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,ProductName
0,1,AR-5381,NaN,Adjustable Race
1,2,BA-8327,NaN,Bearing Ball
2,3,BE-2349,NaN,BB Ball Bearing
3,4,BE-2908,NaN,Headset Ball Bearings
4,5,BL-2036,NaN,Blade
5,6,CA-5965,NaN,LL Crankarm
6,7,CA-6738,NaN,ML Crankarm
7,8,CA-7457,NaN,HL Crankarm
8,9,CB-2903,NaN,Chainring Bolts
9,10,CN-6137,NaN,Chainring Nut

#### Using SQL: Display ProductName, DealerPrice only for those rows where the DealerPrice > 10. Limit your output to only 10 rows

In [16]:
sqldf("""
SELECT
    ProductName, DealerPrice
FROM
    df
WHERE
    DealerPrice > 10
LIMIT 
    10
""")

                  ProductName  DealerPrice
0       Sport-100 Helmet, Red      20.1865
1       Sport-100 Helmet, Red      20.1865
2       Sport-100 Helmet, Red      20.9940
3     Sport-100 Helmet, Black      20.1865
4     Sport-100 Helmet, Black      20.1865
5     Sport-100 Helmet, Black      20.9940
6      Sport-100 Helmet, Blue      20.1865
7      Sport-100 Helmet, Blue      20.1865
8      Sport-100 Helmet, Blue      20.9940
9  Long-Sleeve Logo Jersey, S      28.8404

#### Using Pandas: Display ProductName, DealerPrice only for those rows where the DealerPrice > 10. Limit your output to only 10 rows

In [17]:
df2 = df[['ProductName', 'DealerPrice']]
df2[df2['DealerPrice'] > 10].head(10)

                    ProductName  DealerPrice
211       Sport-100 Helmet, Red      20.1865
212       Sport-100 Helmet, Red      20.1865
213       Sport-100 Helmet, Red      20.9940
214     Sport-100 Helmet, Black      20.1865
215     Sport-100 Helmet, Black      20.1865
216     Sport-100 Helmet, Black      20.9940
219      Sport-100 Helmet, Blue      20.1865
220      Sport-100 Helmet, Blue      20.1865
221      Sport-100 Helmet, Blue      20.9940
225  Long-Sleeve Logo Jersey, S      28.8404

#### Using SQL: Display ProductName, DealerPrice, Color only for those rows where the DealerPrice > 10 AND Color = Silver. Limit your output to only 10 rows

In [18]:
sqldf("""
SELECT
    ProductName, DealerPrice, Color
FROM
    df
WHERE
    DealerPrice > 10
    AND
    Color = 'Silver'
LIMIT 
    10
""")

                      ProductName  DealerPrice   Color
0  HL Mountain Frame - Silver, 42     722.5949  Silver
1  HL Mountain Frame - Silver, 42     744.2727  Silver
2  HL Mountain Frame - Silver, 42     818.7000  Silver
3  HL Mountain Frame - Silver, 44     818.7000  Silver
4  HL Mountain Frame - Silver, 48     818.7000  Silver
5  HL Mountain Frame - Silver, 46     722.5949  Silver
6  HL Mountain Frame - Silver, 46     744.2727  Silver
7  HL Mountain Frame - Silver, 46     818.7000  Silver
8  HL Mountain Frame - Silver, 38     722.5949  Silver
9  HL Mountain Frame - Silver, 38     744.2727  Silver

#### Using Pandas: Display ProductName, DealerPrice, Color only for those rows where the DealerPrice > 10 AND Color = Silver. Limit your output to only 10 rows

In [19]:
df3 = df[['ProductName', 'DealerPrice', 'Color']]
df3[(df3['DealerPrice'] > 10) & (df3['Color'] == 'Silver')].head(10)

                        ProductName  DealerPrice   Color
287  HL Mountain Frame - Silver, 42     722.5949  Silver
288  HL Mountain Frame - Silver, 42     744.2727  Silver
289  HL Mountain Frame - Silver, 42     818.7000  Silver
290  HL Mountain Frame - Silver, 44     818.7000  Silver
291  HL Mountain Frame - Silver, 48     818.7000  Silver
292  HL Mountain Frame - Silver, 46     722.5949  Silver
293  HL Mountain Frame - Silver, 46     744.2727  Silver
294  HL Mountain Frame - Silver, 46     818.7000  Silver
306  HL Mountain Frame - Silver, 38     722.5949  Silver
307  HL Mountain Frame - Silver, 38     744.2727  Silver

#### Using SQL: Group by color. Find the ListPrice AVERAGE per color.

In [20]:
sqldf("""
      SELECT
        Color,
        avg(ListPrice) AS AVG_List
      FROM
        df
      GROUP BY 
        Color
      """)

          Color     AVG_List
0          None    56.470650
1         Black   791.372805
2          Blue   860.105300
3          Grey   125.000000
4         Multi    48.930378
5           Red  1176.605463
6        Silver  1113.593927
7  Silver/Black    64.018571
8         White     9.245000
9        Yellow   918.114130

#### Using Pandas: Group by color. Find the ListPrice AVERAGE per color.

In [21]:
df.groupby('Color')['ListPrice'].mean().reset_index()

          Color    ListPrice
0         Black   791.372805
1          Blue   860.105300
2          Grey   125.000000
3         Multi    48.930378
4           Red  1176.605463
5        Silver  1113.593927
6  Silver/Black    64.018571
7         White     9.245000
8        Yellow   918.114130

In [23]:
df.groupby('Color').agg(ListPrice=("ListPrice",'mean'),medListPrice=("ListPrice",'median')).reset_index()

          Color    ListPrice  medListPrice
0         Black   791.372805      352.9100
1          Blue   860.105300      742.3500
2          Grey   125.000000      125.0000
3         Multi    48.930378       48.0673
4           Red  1176.605463      782.9900
5        Silver  1113.593927      769.4900
6  Silver/Black    64.018571       62.0900
7         White     9.245000        9.2450
8        Yellow   918.114130      742.3500

#### Load the AWProductSubcategory.csv file into a Pandas Dataframe. Name the Dataframe df_s

In [24]:
df_s = pd.read_csv("AWProductSubcategory.csv")
df_s.shape

(37, 3)

In [25]:
df.columns

Index(['ProductKey', 'ProductAlternateKey', 'ProductSubcategoryKey',
       'WeightUnitMeasureCode', 'SizeUnitMeasureCode', 'ProductName',
       'StandardCost', 'FinishedGoodsFlag', 'Color', 'SafetyStockLevel',
       'ReorderPoint', 'ListPrice', 'Size', 'SizeRange', 'Weight',
       'DaysToManufacture', 'ProductLine', 'DealerPrice', 'Class', 'Style',
       'ModelName', 'ProductDescription', 'StartDate', 'EndDate', 'Status'],
      dtype='object')

In [26]:
df_s.columns

Index(['ProductSubcategoryKey', 'ProductCategory', 'ProductSubcategoryName'], dtype='object')

#### Using SQL: Join the df and df_s Dataframes by the ProductSubcategoryKey column. Display ProductAlternateKey, ProductName, ProductSubcategoryKey, ProductCategory, ProductSubcategoryName. Limit your output to only 10 rows

In [27]:
df_final = sqldf("""
SELECT 
    a.ProductAlternateKey, a.ProductName, a.ProductSubcategoryKey, b.ProductCategory, b.ProductSubcategoryName
FROM
    df AS a
INNER JOIN
    df_s AS b
    ON 
    a.ProductSubcategoryKey = b.ProductSubcategoryKey
LIMIT 10
""")

df_final

,ProductAlternateKey,ProductName,ProductSubcategoryKey,ProductCategory,ProductSubcategoryName
0,FR-R92B-58,"HL Road Frame - Black, 58",14.0,Components,Road Frames
1,FR-R92R-58,"HL Road Frame - Red, 58",14.0,Components,Road Frames
2,HL-U509-R,"Sport-100 Helmet, Red",31.0,Accessories,Helmets
3,HL-U509-R,"Sport-100 Helmet, Red",31.0,Accessories,Helmets
4,HL-U509-R,"Sport-100 Helmet, Red",31.0,Accessories,Helmets
5,HL-U509,"Sport-100 Helmet, Black",31.0,Accessories,Helmets
6,HL-U509,"Sport-100 Helmet, Black",31.0,Accessories,Helmets
7,HL-U509,"Sport-100 Helmet, Black",31.0,Accessories,Helmets
8,SO-B909-M,"Mountain Bike Socks, M",23.0,Clothing,Socks
9,SO-B909-L,"Mountain Bike Socks, L",23.0,Clothing,Socks

#### Using Pandas: Join the df and df_s Dataframes by the ProductSubcategoryKey column. Display ProductAlternateKey, ProductName, ProductSubcategoryKey, ProductCategory, ProductSubcategoryName. Limit your output to only 10 rows

In [28]:
df_final2 = pd.merge(df, df_s, on='ProductSubcategoryKey')

df_final2[['ProductAlternateKey', 'ProductName', 'ProductSubcategoryKey', 'ProductCategory', 'ProductSubcategoryName']].head(10)

,ProductAlternateKey,ProductName,ProductSubcategoryKey,ProductCategory,ProductSubcategoryName
0,FR-R92B-58,"HL Road Frame - Black, 58",14.0,Components,Road Frames
1,FR-R92R-58,"HL Road Frame - Red, 58",14.0,Components,Road Frames
2,FR-R92R-62,"HL Road Frame - Red, 62",14.0,Components,Road Frames
3,FR-R92R-62,"HL Road Frame - Red, 62",14.0,Components,Road Frames
4,FR-R92R-62,"HL Road Frame - Red, 62",14.0,Components,Road Frames
5,FR-R92R-44,"HL Road Frame - Red, 44",14.0,Components,Road Frames
6,FR-R92R-44,"HL Road Frame - Red, 44",14.0,Components,Road Frames
7,FR-R92R-44,"HL Road Frame - Red, 44",14.0,Components,Road Frames
8,FR-R92R-48,"HL Road Frame - Red, 48",14.0,Components,Road Frames
9,FR-R92R-48,"HL Road Frame - Red, 48",14.0,Components,Road Frames